# Generated by Django 6.0 on 2025-12-06 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PESSOAL', 'Pessoal'), ('PROFISSIONAL', 'Profissional')], default='PESSOAL', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=120)),
                ('prioridade', models.CharField(choices=[('URGENTE', 'Urgente'), ('ALTO', 'Alto'), ('NORMAL', 'Normal'), ('BAIXO', 'Baixo'), ('PLANEJADO', 'Planejado')], default='NORMAL', max_length=9)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ANDAMENTO', 'Andamento'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=9)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('com_lembrete', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.CharField(max_length=255)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.tarefa')),
            ],
        ),
    ]
