# Generated by Django 6.0 on 2025-12-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('URGENTE', 'Urgente'), ('NORMAL', 'Normal'), ('BAIXO', 'Baixo')], default='NORMAL', max_length=9),
        ),
    ]
