# Generated by Django 6.0 on 2025-12-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_alter_tarefa_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
