# Generated by Django 6.0 on 2025-12-13 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_tarefa_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='usuario',
            new_name='criador',
        ),
    ]
