# Generated by Django 6.0 on 2025-12-14 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_rename_usuario_tarefa_criador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ANDAMENTO', 'Andamento'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=9)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.tarefa')),
            ],
        ),
    ]
