# Generated by Django 6.0 on 2025-12-06 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
