# Generated by Django 6.0 on 2026-02-15 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entretenimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('FILME', 'Filme'), ('SERIE', 'Série'), ('LIVRO', 'Livro'), ('JOGO', 'Jogo'), ('CULTURA', 'Cultura')], max_length=10, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ANDAMENTO', 'Andamento'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=10)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
